export type AchievementCategory =
  | "fitness"
  | "skills"
  | "career"
  | "education"
  | "social"
  | "adventure"
  | "creative";

export interface AchievementMilestone {
  id: string;
  title: string;
  hoursRequired: number;
  category: AchievementCategory;
  icon: string;
  roastLine: string;
}

// All non-scalable achievements with hour costs — the "store" you shop from
export const ACHIEVEMENTS: AchievementMilestone[] = [
  // ── FITNESS ──────────────────────────────────────
  {
    id: "get-jacked",
    title: "Get absolutely jacked",
    hoursRequired: 400,
    category: "fitness",
    icon: "💪",
    roastLine: "Your in-game character has better stats than you and it doesn't even eat.",
  },
  {
    id: "get-six-pack",
    title: "Get visible abs",
    hoursRequired: 150,
    category: "fitness",
    icon: "🏋️",
    roastLine: "The only six-pack you've been working on comes in cans.",
  },
  {
    id: "run-marathon",
    title: "Train for and run a marathon",
    hoursRequired: 200,
    category: "fitness",
    icon: "🏃",
    roastLine: "All that cardio dodging skill shots and you're still winded going up stairs.",
  },
  {
    id: "learn-swimming",
    title: "Learn to swim properly",
    hoursRequired: 50,
    category: "fitness",
    icon: "🏊",
    roastLine: "You've been drowning in ranked for years. At least in a pool there's a shallow end.",
  },
  {
    id: "meditation",
    title: "Build a deep meditation practice",
    hoursRequired: 300,
    category: "fitness",
    icon: "🧘",
    roastLine: "300 hours of sitting still and you'd come out calm instead of tilted.",
  },
  {
    id: "yoga-mastery",
    title: "Master yoga",
    hoursRequired: 500,
    category: "fitness",
    icon: "🧎",
    roastLine: "Your spine has been filing complaints since hour 200.",
  },
  {
    id: "martial-arts",
    title: "Earn your first martial arts belt",
    hoursRequired: 150,
    category: "fitness",
    icon: "🥋",
    roastLine: "150 hours in a dojo and you'd be dangerous for real. Not just in character select.",
  },
  {
    id: "climb-kilimanjaro",
    title: "Train for & climb Kilimanjaro",
    hoursRequired: 250,
    category: "fitness",
    icon: "🏔️",
    roastLine: "5,895 meters above sea level. Your MMR never climbed that high.",
  },
  {
    id: "triathlon",
    title: "Complete a triathlon",
    hoursRequired: 300,
    category: "fitness",
    icon: "🏅",
    roastLine: "Three sports in one day. You can't even commit to one hero.",
  },
  {
    id: "handstand",
    title: "Hold a freestanding handstand",
    hoursRequired: 100,
    category: "fitness",
    icon: "🤸",
    roastLine: "100 hours and you'd be doing handstands at parties. More impressive than your match history.",
  },
  {
    id: "boxing",
    title: "Train boxing and spar competitively",
    hoursRequired: 250,
    category: "fitness",
    icon: "🥊",
    roastLine: "All that desk slamming finally put to good use.",
  },
  {
    id: "splits",
    title: "Achieve full splits",
    hoursRequired: 80,
    category: "fitness",
    icon: "🦵",
    roastLine: "More flexible than your hero pool.",
  },
  {
    id: "calisthenics",
    title: "Master muscle-ups and planches",
    hoursRequired: 350,
    category: "fitness",
    icon: "🏋️‍♂️",
    roastLine: "You've got the grind mentality. Your body's just been waiting for you to use it.",
  },

  // ── SKILLS ───────────────────────────────────────
  {
    id: "driving-license",
    title: "Get a driving license",
    hoursRequired: 50,
    category: "skills",
    icon: "🚗",
    roastLine: "You could've been doing burnouts instead of grinding battlepass.",
  },
  {
    id: "learn-guitar",
    title: "Play guitar at a campfire",
    hoursRequired: 150,
    category: "skills",
    icon: "🎸",
    roastLine: "Everyone at the campfire would be asking you to play. Pudge hooks don't impress anyone outdoors.",
  },
  {
    id: "learn-piano",
    title: "Play piano beautifully",
    hoursRequired: 500,
    category: "skills",
    icon: "🎹",
    roastLine: "Your fingers are fast enough from gaming. Imagine what they'd sound like on a piano.",
  },
  {
    id: "learn-photography",
    title: "Become a solid photographer",
    hoursRequired: 300,
    category: "skills",
    icon: "📷",
    roastLine: "Your screenshots folder is massive. A camera would've given you ones worth printing.",
  },
  {
    id: "learn-drawing",
    title: "Learn to draw portraits",
    hoursRequired: 500,
    category: "skills",
    icon: "✏️",
    roastLine: "You could've drawn your own character skins by now. From scratch.",
  },
  {
    id: "first-aid",
    title: "Get first aid certified",
    hoursRequired: 20,
    category: "skills",
    icon: "🩹",
    roastLine: "20 hours. That's it. Someone might owe you their life.",
  },
  {
    id: "scuba-diving",
    title: "Get scuba diving certified",
    hoursRequired: 40,
    category: "skills",
    icon: "🤿",
    roastLine: "The ocean floor is deeper than your MMR. And way more interesting.",
  },
  {
    id: "woodworking",
    title: "Build furniture from scratch",
    hoursRequired: 300,
    category: "skills",
    icon: "🪑",
    roastLine: "Your gaming chair cost $400. You could've built a better one.",
  },
  {
    id: "bartending",
    title: "Master cocktail making",
    hoursRequired: 100,
    category: "skills",
    icon: "🍸",
    roastLine: "You'd be making drinks at parties that people talk about. The Discord call can wait.",
  },
  {
    id: "motorcycle-license",
    title: "Get a motorcycle license",
    hoursRequired: 40,
    category: "skills",
    icon: "🏍️",
    roastLine: "40 hours. That's all it takes. You'd be on two wheels by now.",
  },
  {
    id: "sailing",
    title: "Learn to sail a boat",
    hoursRequired: 100,
    category: "skills",
    icon: "⛵",
    roastLine: "You could captain a boat. The ocean doesn't have a surrender vote.",
  },
  {
    id: "public-speaking",
    title: "Become a confident speaker",
    hoursRequired: 100,
    category: "skills",
    icon: "🎤",
    roastLine: "You've been yelling at strangers online for years. Same energy, better audience.",
  },
  {
    id: "chess-mastery",
    title: "Get really good at chess",
    hoursRequired: 800,
    category: "skills",
    icon: "♟️",
    roastLine: "At least this strategy game makes you look smart at cafés.",
  },
  {
    id: "juggling",
    title: "Learn to juggle 5 balls",
    hoursRequired: 150,
    category: "skills",
    icon: "🤹",
    roastLine: "You've been juggling your sleep schedule for years already.",
  },
  {
    id: "lockpicking",
    title: "Learn lockpicking",
    hoursRequired: 50,
    category: "skills",
    icon: "🔓",
    roastLine: "Honestly more useful than anything you've ever gotten from a loot box.",
  },
  {
    id: "magic-tricks",
    title: "Learn impressive card magic",
    hoursRequired: 200,
    category: "skills",
    icon: "🃏",
    roastLine: "200 hours of card magic and you'd be the most interesting person at any table.",
  },
  {
    id: "welding",
    title: "Learn to weld",
    hoursRequired: 200,
    category: "skills",
    icon: "🔥",
    roastLine: "Sparks flying, metal bending, and you walk out with something you built. IRL crafting.",
  },
  {
    id: "sign-language",
    title: "Learn sign language",
    hoursRequired: 200,
    category: "skills",
    icon: "🤟",
    roastLine: "Communicate without a mic. Your teammates wish you would.",
  },
  {
    id: "sewing",
    title: "Learn to sew your own clothes",
    hoursRequired: 150,
    category: "skills",
    icon: "🧵",
    roastLine: "You've spent more on skins than clothes. 150 hours and you'd be making your own.",
  },
  {
    id: "car-mechanic",
    title: "Learn basic car mechanics",
    hoursRequired: 100,
    category: "skills",
    icon: "🔧",
    roastLine: "Next time your car breaks down you'd fix it yourself. Can't blame lag on a carburetor.",
  },

  // ── CAREER & MONEY ──────────────────────────────
  {
    id: "learn-to-code",
    title: "Learn to code (job-ready)",
    hoursRequired: 500,
    category: "career",
    icon: "💻",
    roastLine: "You could've built the game you're addicted to. Well, a worse version.",
  },
  {
    id: "freelance-skill",
    title: "Build a freelance business",
    hoursRequired: 400,
    category: "career",
    icon: "💼",
    roastLine: "You could be making money on the side by now. Your quest log wouldn't miss you.",
  },
  {
    id: "real-estate-license",
    title: "Get a real estate license",
    hoursRequired: 150,
    category: "career",
    icon: "🏠",
    roastLine: "You'd be selling houses while other people grind for virtual ones.",
  },
  {
    id: "personal-trainer-cert",
    title: "Get a personal trainer certification",
    hoursRequired: 120,
    category: "career",
    icon: "📋",
    roastLine: "Help others get jacked while you still can't do 10 push-ups.",
  },
  {
    id: "pilot-license",
    title: "Get a private pilot license",
    hoursRequired: 110,
    category: "career",
    icon: "✈️",
    roastLine: "Flight Sim was just the tutorial. 110 hours and you'd have the real license.",
  },
  {
    id: "youtube-channel",
    title: "Build a YouTube channel to 10K subs",
    hoursRequired: 500,
    category: "career",
    icon: "📺",
    roastLine: "People would watch you ON PURPOSE. Not just in a death recap.",
  },
  {
    id: "startup",
    title: "Launch an actual startup",
    hoursRequired: 1000,
    category: "career",
    icon: "🚀",
    roastLine: "1,000 hours building something. By now someone might be paying you for it.",
  },
  {
    id: "emt-cert",
    title: "Become a certified EMT",
    hoursRequired: 200,
    category: "career",
    icon: "🚑",
    roastLine: "You feed in ranked every night. As an EMT at least the feeding saves someone.",
  },
  {
    id: "stock-trading",
    title: "Learn serious stock trading",
    hoursRequired: 300,
    category: "career",
    icon: "📊",
    roastLine: "Gamble on the stock market. At least that pays dividends.",
  },

  // ── EDUCATION ───────────────────────────────────
  {
    id: "learn-language",
    title: "Learn a new language (conversational)",
    hoursRequired: 600,
    category: "education",
    icon: "🗣️",
    roastLine: "You could trash talk in TWO languages. Cyka blyat doesn't count.",
  },
  {
    id: "learn-language-basic",
    title: "Learn basic survival phrases (5 languages)",
    hoursRequired: 100,
    category: "education",
    icon: "🌍",
    roastLine: "You've memorized every callout on Dust2 but couldn't navigate a foreign subway.",
  },
  {
    id: "speed-reading",
    title: "Master speed reading",
    hoursRequired: 40,
    category: "education",
    icon: "📖",
    roastLine: "You read patch notes the day they drop. Imagine that energy on books.",
  },
  {
    id: "astronomy",
    title: "Learn amateur astronomy",
    hoursRequired: 100,
    category: "education",
    icon: "🔭",
    roastLine: "The night sky is more interesting than your loading screen.",
  },
  {
    id: "finance-literacy",
    title: "Master personal finance & investing",
    hoursRequired: 100,
    category: "education",
    icon: "📈",
    roastLine: "Your money's been sitting there doing nothing. Kind of like your duo in lane.",
  },
  {
    id: "philosophy",
    title: "Study philosophy deeply",
    hoursRequired: 300,
    category: "education",
    icon: "🏛️",
    roastLine: "Socrates didn't know his MMR and seemed pretty content about it.",
  },
  {
    id: "data-science",
    title: "Learn data science & machine learning",
    hoursRequired: 500,
    category: "education",
    icon: "🧠",
    roastLine: "Your GPU was right there this whole time, doing nothing useful.",
  },
  {
    id: "history-deep-dive",
    title: "Become a history buff (read 50 history books)",
    hoursRequired: 400,
    category: "education",
    icon: "📜",
    roastLine: "You know every Civilization tech tree by heart. The real history is wilder.",
  },
  {
    id: "math-mastery",
    title: "Learn calculus and linear algebra",
    hoursRequired: 300,
    category: "education",
    icon: "🔢",
    roastLine: "Calculate your win rate in your head. Then cry.",
  },

  // ── CREATIVE ────────────────────────────────────
  {
    id: "cook-well",
    title: "Learn to cook like a chef",
    hoursRequired: 350,
    category: "creative",
    icon: "👨‍🍳",
    roastLine: "Gordon Ramsay would be disappointed. Your microwave is thriving though.",
  },
  {
    id: "write-novel",
    title: "Write a novel",
    hoursRequired: 500,
    category: "creative",
    icon: "📝",
    roastLine: "NaNoWriMo is 50k words in a month. You had years.",
  },
  {
    id: "learn-pottery",
    title: "Learn pottery",
    hoursRequired: 100,
    category: "creative",
    icon: "🏺",
    roastLine: "Cheaper than therapy and you get a mug out of it.",
  },
  {
    id: "music-production",
    title: "Produce your own music",
    hoursRequired: 400,
    category: "creative",
    icon: "🎧",
    roastLine: "You've got the taste already. 400 hours and you'd be the one making it.",
  },
  {
    id: "film-short",
    title: "Write & film a short movie",
    hoursRequired: 200,
    category: "creative",
    icon: "🎬",
    roastLine: "Direct something people would watch on purpose.",
  },
  {
    id: "sourdough",
    title: "Master sourdough bread",
    hoursRequired: 50,
    category: "creative",
    icon: "🍞",
    roastLine: "50 hours and you'd be pulling fresh bread out of the oven. Your microwave feels threatened.",
  },
  {
    id: "baking",
    title: "Become an excellent baker",
    hoursRequired: 250,
    category: "creative",
    icon: "🧁",
    roastLine: "Nobody at a dinner party has ever asked about your rank. They would ask about your cake though.",
  },
  {
    id: "tattooing",
    title: "Learn to tattoo",
    hoursRequired: 500,
    category: "creative",
    icon: "💉",
    roastLine: "At least a bad tattoo starts a conversation.",
  },
  {
    id: "animation",
    title: "Learn 2D animation",
    hoursRequired: 400,
    category: "creative",
    icon: "🎞️",
    roastLine: "400 hours and your characters would be moving on screen. Ones you designed yourself.",
  },
  {
    id: "leatherworking",
    title: "Learn leatherworking",
    hoursRequired: 150,
    category: "creative",
    icon: "👜",
    roastLine: "You'd be making wallets and bags that last longer than any skin you've bought.",
  },
  {
    id: "graphic-design",
    title: "Master graphic design",
    hoursRequired: 400,
    category: "creative",
    icon: "🎨",
    roastLine: "400 hours of design and people start paying you for it. Weird how that works.",
  },
  {
    id: "singing",
    title: "Learn to sing well",
    hoursRequired: 200,
    category: "creative",
    icon: "🎵",
    roastLine: "You've been projecting your voice in comms for years. Might as well sound good doing it.",
  },

  // ── SOCIAL & ADVENTURE ──────────────────────────
  {
    id: "find-love",
    title: "Go on 100 dates (and probably find love)",
    hoursRequired: 500,
    category: "social",
    icon: "❤️",
    roastLine: "500 hours of putting yourself out there. Statistically you'd have found someone. Less toxic than solo queue, too.",
  },
  {
    id: "volunteer",
    title: "Volunteer 200 hours for a cause",
    hoursRequired: 200,
    category: "social",
    icon: "🤝",
    roastLine: "200 hours helping people. Your teammates would've loved that energy.",
  },
  {
    id: "travel-backpack",
    title: "Backpack across a continent",
    hoursRequired: 800,
    category: "adventure",
    icon: "🎒",
    roastLine: "800 hours of open world games and you've never seen the Andes.",
  },
  {
    id: "skydiving-cert",
    title: "Get a skydiving license",
    hoursRequired: 30,
    category: "adventure",
    icon: "🪂",
    roastLine: "30 hours and you're literally falling from the sky. Ranked never got your heart rate this high.",
  },
  {
    id: "surf",
    title: "Learn to surf",
    hoursRequired: 80,
    category: "adventure",
    icon: "🏄",
    roastLine: "80 hours in the ocean catching waves. Better than catching Ls.",
  },
  {
    id: "rock-climbing",
    title: "Get good at rock climbing",
    hoursRequired: 200,
    category: "adventure",
    icon: "🧗",
    roastLine: "Your hands grip a mouse 8 hours a day. They'd do just fine on a cliff face.",
  },
  {
    id: "dog-training",
    title: "Adopt & fully train a dog",
    hoursRequired: 250,
    category: "social",
    icon: "🐕",
    roastLine: "A dog loves you even after a 10-game loss streak. Can your duo say that?",
  },
  {
    id: "stand-up",
    title: "Write & perform a stand-up set",
    hoursRequired: 100,
    category: "social",
    icon: "😂",
    roastLine: "You've been a joke in ranked for years. Monetize it.",
  },
  {
    id: "garden",
    title: "Build a thriving garden",
    hoursRequired: 100,
    category: "social",
    icon: "🌱",
    roastLine: "Your garden would be thriving by now. It'd outlast your rank, too.",
  },
  {
    id: "snowboarding",
    title: "Learn to snowboard",
    hoursRequired: 80,
    category: "adventure",
    icon: "🏂",
    roastLine: "No ranking system on a powder day. That's the whole point.",
  },
  {
    id: "scuba-advanced",
    title: "Explore 20 dive sites worldwide",
    hoursRequired: 200,
    category: "adventure",
    icon: "🐠",
    roastLine: "20 dive sites around the world. The draw distance is unreal.",
  },
  {
    id: "road-trip",
    title: "Drive across an entire country",
    hoursRequired: 150,
    category: "adventure",
    icon: "🛣️",
    roastLine: "Thousands of miles of highway and nobody pinging you to group up.",
  },
  {
    id: "camping-survival",
    title: "Learn wilderness survival",
    hoursRequired: 100,
    category: "adventure",
    icon: "🏕️",
    roastLine: "Can't blame lag when a bear shows up.",
  },
  {
    id: "dance",
    title: "Learn to dance (salsa or swing)",
    hoursRequired: 150,
    category: "social",
    icon: "💃",
    roastLine: "Your wrist already has the coordination. The rest of your body just needs to catch up.",
  },
  {
    id: "podcast",
    title: "Launch a podcast (50 episodes)",
    hoursRequired: 300,
    category: "social",
    icon: "🎙️",
    roastLine: "You already talk into a mic about stuff you care about. You do it in Discord every night.",
  },
  {
    id: "mentor",
    title: "Mentor 10 young people",
    hoursRequired: 200,
    category: "social",
    icon: "🧑‍🏫",
    roastLine: "You've been telling people what to do in games for years. Someone might as well pay you for it.",
  },
  {
    id: "paragliding",
    title: "Learn to paraglide",
    hoursRequired: 60,
    category: "adventure",
    icon: "🪁",
    roastLine: "60 hours strapped to a wing with nothing below you. Ranked anxiety was just practice.",
  },
  {
    id: "marathon-swimming",
    title: "Swim across a lake or channel",
    hoursRequired: 300,
    category: "adventure",
    icon: "🌊",
    roastLine: "300 hours in open water. No lanes, no team. Just you figuring it out.",
  },
];
