export type AchievementCategory =
  | "fitness"
  | "skills"
  | "career"
  | "education"
  | "social"
  | "adventure"
  | "creative";

export interface AchievementMilestone {
  id: string;
  title: string;
  hoursRequired: number;
  category: AchievementCategory;
  icon: string;
  roastLine: string;
}

// All non-scalable achievements with hour costs — the "store" you shop from
export const ACHIEVEMENTS: AchievementMilestone[] = [
  // ── FITNESS ──────────────────────────────────────
  {
    id: "get-jacked",
    title: "Get absolutely jacked",
    hoursRequired: 400,
    category: "fitness",
    icon: "💪",
    roastLine: "Your character is maxed out. You? Still base stats.",
  },
  {
    id: "get-six-pack",
    title: "Get visible abs",
    hoursRequired: 150,
    category: "fitness",
    icon: "🏋️",
    roastLine: "The only six-pack you've been working on comes in cans.",
  },
  {
    id: "run-marathon",
    title: "Train for and run a marathon",
    hoursRequired: 200,
    category: "fitness",
    icon: "🏃",
    roastLine: "You've run from enough teamfights. Might as well make it official.",
  },
  {
    id: "learn-swimming",
    title: "Learn to swim properly",
    hoursRequired: 50,
    category: "fitness",
    icon: "🏊",
    roastLine: "You've been drowning in ranked. At least this drowning is fixable.",
  },
  {
    id: "meditation",
    title: "Build a deep meditation practice",
    hoursRequired: 300,
    category: "fitness",
    icon: "🧘",
    roastLine: "Inner peace > Inner rage at your ranked teammates.",
  },
  {
    id: "yoga-mastery",
    title: "Master yoga",
    hoursRequired: 500,
    category: "fitness",
    icon: "🧎",
    roastLine: "Your posture from gaming would've been fixed 480 hours ago.",
  },
  {
    id: "martial-arts",
    title: "Earn your first martial arts belt",
    hoursRequired: 150,
    category: "fitness",
    icon: "🥋",
    roastLine: "You could actually fight, not just pick fighters in a game.",
  },
  {
    id: "climb-kilimanjaro",
    title: "Train for & climb Kilimanjaro",
    hoursRequired: 250,
    category: "fitness",
    icon: "🏔️",
    roastLine: "Peak gaming → actual peak. 5,895m of 'what if.'",
  },
  {
    id: "triathlon",
    title: "Complete a triathlon",
    hoursRequired: 300,
    category: "fitness",
    icon: "🏅",
    roastLine: "Three sports in one day. You can't even commit to one hero.",
  },
  {
    id: "handstand",
    title: "Hold a freestanding handstand",
    hoursRequired: 100,
    category: "fitness",
    icon: "🤸",
    roastLine: "Flip your world upside down. Literally.",
  },
  {
    id: "boxing",
    title: "Train boxing and spar competitively",
    hoursRequired: 250,
    category: "fitness",
    icon: "🥊",
    roastLine: "Hit something that isn't your keyboard for once.",
  },
  {
    id: "splits",
    title: "Achieve full splits",
    hoursRequired: 80,
    category: "fitness",
    icon: "🦵",
    roastLine: "More flexible than your hero pool.",
  },
  {
    id: "calisthenics",
    title: "Master muscle-ups and planches",
    hoursRequired: 350,
    category: "fitness",
    icon: "🏋️‍♂️",
    roastLine: "Your body could've been the ultimate weapon. Instead you bought skins.",
  },

  // ── SKILLS ───────────────────────────────────────
  {
    id: "driving-license",
    title: "Get a driving license",
    hoursRequired: 50,
    category: "skills",
    icon: "🚗",
    roastLine: "You could've been doing burnouts instead of grinding battlepass.",
  },
  {
    id: "learn-guitar",
    title: "Play guitar at a campfire",
    hoursRequired: 150,
    category: "skills",
    icon: "🎸",
    roastLine: "Instead of being the Pudge main, you'd be the one everyone wants at parties.",
  },
  {
    id: "learn-piano",
    title: "Play piano beautifully",
    hoursRequired: 500,
    category: "skills",
    icon: "🎹",
    roastLine: "Instead of mashing QWER, you could've been playing Chopin.",
  },
  {
    id: "learn-photography",
    title: "Become a solid photographer",
    hoursRequired: 300,
    category: "skills",
    icon: "📷",
    roastLine: "Your screenshots folder is massive. Imagine if those were actual good photos.",
  },
  {
    id: "learn-drawing",
    title: "Learn to draw portraits",
    hoursRequired: 500,
    category: "skills",
    icon: "✏️",
    roastLine: "You could've drawn your own character skins instead of buying them.",
  },
  {
    id: "first-aid",
    title: "Get first aid certified",
    hoursRequired: 20,
    category: "skills",
    icon: "🩹",
    roastLine: "You can't save your teammates, but you could've saved actual lives.",
  },
  {
    id: "scuba-diving",
    title: "Get scuba diving certified",
    hoursRequired: 40,
    category: "skills",
    icon: "🤿",
    roastLine: "Explore the ocean floor instead of the depths of your MMR.",
  },
  {
    id: "woodworking",
    title: "Build furniture from scratch",
    hoursRequired: 300,
    category: "skills",
    icon: "🪑",
    roastLine: "Your gaming chair cost $400. You could've built a better one.",
  },
  {
    id: "bartending",
    title: "Master cocktail making",
    hoursRequired: 100,
    category: "skills",
    icon: "🍸",
    roastLine: "You'd be the coolest person at every party. Instead, you're in a Discord call.",
  },
  {
    id: "motorcycle-license",
    title: "Get a motorcycle license",
    hoursRequired: 40,
    category: "skills",
    icon: "🏍️",
    roastLine: "Vroom vroom > pew pew.",
  },
  {
    id: "sailing",
    title: "Learn to sail a boat",
    hoursRequired: 100,
    category: "skills",
    icon: "⛵",
    roastLine: "Captain of a ranked team → Captain of an actual boat.",
  },
  {
    id: "public-speaking",
    title: "Become a confident speaker",
    hoursRequired: 100,
    category: "skills",
    icon: "🎤",
    roastLine: "You've flamed teammates for years. Channel that energy constructively.",
  },
  {
    id: "chess-mastery",
    title: "Get really good at chess",
    hoursRequired: 800,
    category: "skills",
    icon: "♟️",
    roastLine: "At least this strategy game makes you look smart at cafés.",
  },
  {
    id: "juggling",
    title: "Learn to juggle 5 balls",
    hoursRequired: 150,
    category: "skills",
    icon: "🤹",
    roastLine: "You've been juggling your sleep schedule for years already.",
  },
  {
    id: "lockpicking",
    title: "Learn lockpicking",
    hoursRequired: 50,
    category: "skills",
    icon: "🔓",
    roastLine: "Unlock doors instead of loot boxes.",
  },
  {
    id: "magic-tricks",
    title: "Learn impressive card magic",
    hoursRequired: 200,
    category: "skills",
    icon: "🃏",
    roastLine: "Make things disappear. Like your hours already do, but cooler.",
  },
  {
    id: "welding",
    title: "Learn to weld",
    hoursRequired: 200,
    category: "skills",
    icon: "🔥",
    roastLine: "Forge metal instead of forging ahead to another loss.",
  },
  {
    id: "sign-language",
    title: "Learn sign language",
    hoursRequired: 200,
    category: "skills",
    icon: "🤟",
    roastLine: "Communicate without a mic. Revolutionary.",
  },
  {
    id: "sewing",
    title: "Learn to sew your own clothes",
    hoursRequired: 150,
    category: "skills",
    icon: "🧵",
    roastLine: "Design real outfits instead of buying character skins.",
  },
  {
    id: "car-mechanic",
    title: "Learn basic car mechanics",
    hoursRequired: 100,
    category: "skills",
    icon: "🔧",
    roastLine: "Fix an engine instead of blaming lag.",
  },

  // ── CAREER & MONEY ──────────────────────────────
  {
    id: "learn-to-code",
    title: "Learn to code (job-ready)",
    hoursRequired: 500,
    category: "career",
    icon: "💻",
    roastLine: "You could've built the game you're addicted to. Well, a worse version.",
  },
  {
    id: "freelance-skill",
    title: "Build a freelance business",
    hoursRequired: 400,
    category: "career",
    icon: "💼",
    roastLine: "Side income > side quests.",
  },
  {
    id: "real-estate-license",
    title: "Get a real estate license",
    hoursRequired: 150,
    category: "career",
    icon: "🏠",
    roastLine: "You'd be selling houses instead of grinding for a virtual one.",
  },
  {
    id: "personal-trainer-cert",
    title: "Get a personal trainer certification",
    hoursRequired: 120,
    category: "career",
    icon: "📋",
    roastLine: "Help others get jacked while you still can't do 10 push-ups.",
  },
  {
    id: "pilot-license",
    title: "Get a private pilot license",
    hoursRequired: 110,
    category: "career",
    icon: "✈️",
    roastLine: "Fly an actual plane instead of pretending in MSFS.",
  },
  {
    id: "youtube-channel",
    title: "Build a YouTube channel to 10K subs",
    hoursRequired: 500,
    category: "career",
    icon: "📺",
    roastLine: "People would watch you ON PURPOSE instead of in a death recap.",
  },
  {
    id: "startup",
    title: "Launch an actual startup",
    hoursRequired: 1000,
    category: "career",
    icon: "🚀",
    roastLine: "Build something people pay for instead of something you pay for.",
  },
  {
    id: "emt-cert",
    title: "Become a certified EMT",
    hoursRequired: 200,
    category: "career",
    icon: "🚑",
    roastLine: "Save actual lives instead of feeding in ranked.",
  },
  {
    id: "stock-trading",
    title: "Learn serious stock trading",
    hoursRequired: 300,
    category: "career",
    icon: "📊",
    roastLine: "Gamble on the stock market instead. At least it pays dividends.",
  },

  // ── EDUCATION ───────────────────────────────────
  {
    id: "learn-language",
    title: "Learn a new language (conversational)",
    hoursRequired: 600,
    category: "education",
    icon: "🗣️",
    roastLine: "You could trash talk in TWO languages. Cyka blyat doesn't count.",
  },
  {
    id: "learn-language-basic",
    title: "Learn basic survival phrases (5 languages)",
    hoursRequired: 100,
    category: "education",
    icon: "🌍",
    roastLine: "Navigate 5 countries vs. navigate 5 maps. One is more useful.",
  },
  {
    id: "speed-reading",
    title: "Master speed reading",
    hoursRequired: 40,
    category: "education",
    icon: "📖",
    roastLine: "Read patch notes faster. Or, y'know, actual books.",
  },
  {
    id: "astronomy",
    title: "Learn amateur astronomy",
    hoursRequired: 100,
    category: "education",
    icon: "🔭",
    roastLine: "The night sky is more interesting than your loading screen.",
  },
  {
    id: "finance-literacy",
    title: "Master personal finance & investing",
    hoursRequired: 100,
    category: "education",
    icon: "📈",
    roastLine: "Your actual money could've been growing this whole time.",
  },
  {
    id: "philosophy",
    title: "Study philosophy deeply",
    hoursRequired: 300,
    category: "education",
    icon: "🏛️",
    roastLine: "Ponder the meaning of life instead of the meaning of your rank.",
  },
  {
    id: "data-science",
    title: "Learn data science & machine learning",
    hoursRequired: 500,
    category: "education",
    icon: "🧠",
    roastLine: "Train neural networks instead of training your MMR downward.",
  },
  {
    id: "history-deep-dive",
    title: "Become a history buff (read 50 history books)",
    hoursRequired: 400,
    category: "education",
    icon: "📜",
    roastLine: "Know about actual wars instead of just digital ones.",
  },
  {
    id: "math-mastery",
    title: "Learn calculus and linear algebra",
    hoursRequired: 300,
    category: "education",
    icon: "🔢",
    roastLine: "Calculate your win rate in your head. Then cry.",
  },

  // ── CREATIVE ────────────────────────────────────
  {
    id: "cook-well",
    title: "Learn to cook like a chef",
    hoursRequired: 350,
    category: "creative",
    icon: "👨‍🍳",
    roastLine: "Gordon Ramsay is disappointed. Your microwave is not.",
  },
  {
    id: "write-novel",
    title: "Write a novel",
    hoursRequired: 500,
    category: "creative",
    icon: "📝",
    roastLine: "NaNoWriMo is 50k words in a month. You had years.",
  },
  {
    id: "learn-pottery",
    title: "Learn pottery",
    hoursRequired: 100,
    category: "creative",
    icon: "🏺",
    roastLine: "Shape clay instead of letting ranked shape your mental health.",
  },
  {
    id: "music-production",
    title: "Produce your own music",
    hoursRequired: 400,
    category: "creative",
    icon: "🎧",
    roastLine: "Drop a beat instead of dropping rank.",
  },
  {
    id: "film-short",
    title: "Write & film a short movie",
    hoursRequired: 200,
    category: "creative",
    icon: "🎬",
    roastLine: "Direct something people actually want to watch.",
  },
  {
    id: "sourdough",
    title: "Master sourdough bread",
    hoursRequired: 50,
    category: "creative",
    icon: "🍞",
    roastLine: "Feed your starter, not your addiction.",
  },
  {
    id: "baking",
    title: "Become an excellent baker",
    hoursRequired: 250,
    category: "creative",
    icon: "🧁",
    roastLine: "Sweet skills > sweet rank badge.",
  },
  {
    id: "tattooing",
    title: "Learn to tattoo",
    hoursRequired: 500,
    category: "creative",
    icon: "💉",
    roastLine: "Permanent ink on skin > permanent stain on your match history.",
  },
  {
    id: "animation",
    title: "Learn 2D animation",
    hoursRequired: 400,
    category: "creative",
    icon: "🎞️",
    roastLine: "Animate your own characters instead of watching them die in-game.",
  },
  {
    id: "leatherworking",
    title: "Learn leatherworking",
    hoursRequired: 150,
    category: "creative",
    icon: "👜",
    roastLine: "Craft real gear instead of virtual gear.",
  },
  {
    id: "graphic-design",
    title: "Master graphic design",
    hoursRequired: 400,
    category: "creative",
    icon: "🎨",
    roastLine: "Design logos people pay for instead of flaming your team's logo.",
  },
  {
    id: "singing",
    title: "Learn to sing well",
    hoursRequired: 200,
    category: "creative",
    icon: "🎵",
    roastLine: "Belt out karaoke instead of yelling callouts nobody listens to.",
  },

  // ── SOCIAL & ADVENTURE ──────────────────────────
  {
    id: "find-love",
    title: "Go on 100 dates (and probably find love)",
    hoursRequired: 500,
    category: "social",
    icon: "❤️",
    roastLine: "Swiping, matching, chatting, actual dates — the full grind. Still less toxic than ranked.",
  },
  {
    id: "volunteer",
    title: "Volunteer 200 hours for a cause",
    hoursRequired: 200,
    category: "social",
    icon: "🤝",
    roastLine: "Make the world better instead of making your team worse.",
  },
  {
    id: "travel-backpack",
    title: "Backpack across a continent",
    hoursRequired: 800,
    category: "adventure",
    icon: "🎒",
    roastLine: "Explore actual open worlds.",
  },
  {
    id: "skydiving-cert",
    title: "Get a skydiving license",
    hoursRequired: 30,
    category: "adventure",
    icon: "🪂",
    roastLine: "Real adrenaline > ranked anxiety.",
  },
  {
    id: "surf",
    title: "Learn to surf",
    hoursRequired: 80,
    category: "adventure",
    icon: "🏄",
    roastLine: "Ride waves, not losing streaks.",
  },
  {
    id: "rock-climbing",
    title: "Get good at rock climbing",
    hoursRequired: 200,
    category: "adventure",
    icon: "🧗",
    roastLine: "Climb actual ranks. Made of rock.",
  },
  {
    id: "dog-training",
    title: "Adopt & fully train a dog",
    hoursRequired: 250,
    category: "social",
    icon: "🐕",
    roastLine: "Unconditional love > conditional ranked queue.",
  },
  {
    id: "stand-up",
    title: "Write & perform a stand-up set",
    hoursRequired: 100,
    category: "social",
    icon: "😂",
    roastLine: "You've been a joke in ranked for years. Monetize it.",
  },
  {
    id: "garden",
    title: "Build a thriving garden",
    hoursRequired: 100,
    category: "social",
    icon: "🌱",
    roastLine: "Grow something real instead of your hours played.",
  },
  {
    id: "snowboarding",
    title: "Learn to snowboard",
    hoursRequired: 80,
    category: "adventure",
    icon: "🏂",
    roastLine: "Shred mountains instead of shredding your MMR.",
  },
  {
    id: "scuba-advanced",
    title: "Explore 20 dive sites worldwide",
    hoursRequired: 200,
    category: "adventure",
    icon: "🐠",
    roastLine: "Discover actual underwater maps. No respawns though.",
  },
  {
    id: "road-trip",
    title: "Drive across an entire country",
    hoursRequired: 150,
    category: "adventure",
    icon: "🛣️",
    roastLine: "Open road > open mid.",
  },
  {
    id: "camping-survival",
    title: "Learn wilderness survival",
    hoursRequired: 100,
    category: "adventure",
    icon: "🏕️",
    roastLine: "Survive in the wild instead of barely surviving in lane.",
  },
  {
    id: "dance",
    title: "Learn to dance (salsa or swing)",
    hoursRequired: 150,
    category: "social",
    icon: "💃",
    roastLine: "Move your body instead of just your mouse.",
  },
  {
    id: "podcast",
    title: "Launch a podcast (50 episodes)",
    hoursRequired: 300,
    category: "social",
    icon: "🎙️",
    roastLine: "People would listen to you on purpose. Novel concept.",
  },
  {
    id: "mentor",
    title: "Mentor 10 young people",
    hoursRequired: 200,
    category: "social",
    icon: "🧑‍🏫",
    roastLine: "Coach actual humans instead of backseat gaming.",
  },
  {
    id: "paragliding",
    title: "Learn to paraglide",
    hoursRequired: 60,
    category: "adventure",
    icon: "🪁",
    roastLine: "Fly through the sky instead of flying off the handle in voice chat.",
  },
  {
    id: "marathon-swimming",
    title: "Swim across a lake or channel",
    hoursRequired: 300,
    category: "adventure",
    icon: "🌊",
    roastLine: "Cross a body of water instead of crossing your team.",
  },
];
